services:
  db:
    image: 'postgres:15-alpine'
    container_name: gestor_db
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: secretpassword
      POSTGRES_DB: gestor_proyectos_db
    # ELIMINADO: ports: - '5432:5432' por seguridad
    volumes:
      - 'pgdata:/var/lib/postgresql/data' # Este volumen sí queda, ¡es para no perder los datos!
    restart: unless-stopped

  backend:
    build:
      context: ./backend
    container_name: gestor_backend
    ports:
      - '3000:3000'
    # ELIMINADOS los volumes de ./backend:/app
    environment:
      - PORT=3000
      - 'DATABASE_URL=postgres://admin:secretpassword@db:5432/gestor_proyectos_db'
    depends_on:
      - db
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
    container_name: gestor_frontend
    ports:
      - '5173:5173'
    # ELIMINADOS los volumes de ./frontend:/app
    environment:
      - 'VITE_API_URL=http://apis-taskmanager.163.176.208.127.sslip.io:3000/api' # ¡Atento a esto para el paso 2!
    depends_on:
      - backend
    restart: unless-stopped

volumes:
  pgdata: null
