services:
  db:
    image: 'postgres:15-alpine'
    container_name: gestor_db
    environment:
      POSTGRES_USER: admin
      # Pasamos la variable sin comillas y sin armarla a mano
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: gestor_proyectos_db
    volumes:
      - 'pgdata:/var/lib/postgresql/data'
    restart: unless-stopped

  backend:
    build:
      context: ./backend
    container_name: gestor_backend
    ports:
      - '3000:3000'
    environment:
      - PORT=3000
      # ATENCIÓN AQUÍ: Ya no la armamos, simplemente pasamos la variable completa
      - DATABASE_URL=${DATABASE_URL}
      - JWT_SECRET=${JWT_SECRET}
      - JWT_EXPIRES_IN=7d
      - FRONTEND_URL=${FRONTEND_URL}
      - GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
      - GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET}
      - GOOGLE_CALLBACK_URL=${GOOGLE_CALLBACK_URL}
      - VAPID_PUBLIC_KEY=${VAPID_PUBLIC_KEY}
      - VAPID_PRIVATE_KEY=${VAPID_PRIVATE_KEY}
      - VAPID_SUBJECT=${VAPID_SUBJECT}
    depends_on:
      - db
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
    container_name: gestor_frontend
    ports:
      - '5173:5173'
    environment:
      - VITE_API_URL=http://apis-taskmanager.163.176.208.127.sslip.io/api
      - VITE_SOCKET_URL=http://apis-taskmanager.163.176.208.127.sslip.io
    # También haz esto dinámico por las dudas
    depends_on:
      - backend
    restart: unless-stopped
    labels:
      - "traefik.http.services.gestor_frontend.loadbalancer.server.port=5173"

volumes:
  pgdata: null
